name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the bug
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Load rule...
        2. Execute with facts...
        3. See error...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Nomos Version
      placeholder: e.g., 0.0.1
    validations:
      required: true
  - type: input
    id: java
    attributes:
      label: Java Version
      placeholder: e.g., 17.0.9
    validations:
      required: true